spring.application.name=store-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/store-manager
spring.datasource.username=postgres
spring.datasource.password=10293

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect